extends: airbnb
env:
  browser: true
  node: true
  es6: true
plugins:
  ['react', 'jsx-a11y']
parser: babel-eslint
rules:
  import/no-unresolved: 0
  react/jsx-filename-extension: [1, { "extensions": [".js"] }]
  react/jsx-indent: ["error", 4]
  jsx-a11y/href-no-hash: off
  indent: ["error", 4, {"SwitchCase": 1}]
  semi: ["error", "never"]
  comma-dangle: 0
  no-alert: 0

